
/// ==================================================================
/// Module.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.Capture.Client
{
  public partial class CaptureModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("4c7444e6-c4af-46c1-9cfa-d9194d3ff0cb"); }
    }

    public override string Name
    {
      get { return "Sungero.Capture"; }
    }

    public override void RegisterTypes()
    {



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.Capture.Client.IModuleClientPublicFunctions, global::Sungero.Capture.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.Capture.Shared.IModuleSharedPublicFunctions, global::Sungero.Capture.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
