
/// ==================================================================
/// ModuleFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Functions
{
  internal static partial class Module
  {
    private static object GetFunctionsContainer()
    {
      return new global::Sungero.SignatureMark.Module.Docflow.Server.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("64f69a45-87e9-428f-8e82-7e6e189907f4");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }
  }
}
namespace Sungero.SignatureMark.Module.Docflow.Server
{
  public partial class ModuleFunctions: global::Sungero.Docflow.Server.ModuleFunctions
  {

  }
}

/// ==================================================================
/// ModuleInitializationInstantiation.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.ModuleInitialization
{
  internal static partial class Module
  {

    private static object GetFunctionsContainer()
    {
      return new global::Sungero.SignatureMark.Module.Docflow.Server.ModuleInitializer();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("64f69a45-87e9-428f-8e82-7e6e189907f4");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.ModuleInitializationNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }

  }
}


/// ==================================================================
/// ModuleJobs.g.cs
/// ==================================================================

namespace Sungero.SignatureMark.Module.Docflow.Server
{
  public partial class ModuleJobs : global::Sungero.Docflow.Server.ModuleJobs
  {

  }
}

/// ==================================================================
/// ModuleServerPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Server
{
  public partial class ModuleServerPublicFunctions : global::Sungero.SignatureMark.Module.Docflow.Server.IModuleServerPublicFunctions
  {
  }
}

namespace Sungero.SignatureMark.Module.Docflow.Server
{
  public partial class ModuleServerPublicFunctions : global::Sungero.SignatureMark.Module.Docflow.Server.IModuleServerPublicFunctions
  {
 
 
 

  }
}

/// ==================================================================
/// ModuleServerInitializationFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Server
{
  public partial class ModuleServerInitializationFunctions : global::Sungero.SignatureMark.Module.Docflow.Server.IModuleServerInitializationFunctions
  {
  }
}


/// ==================================================================
/// ModuleHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Server
{
  public partial class ApprovalRulesFolderHandlers : global::Sungero.Docflow.Server.ApprovalRulesFolderHandlers
  {
    private global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState _filter
    {
      get
      {
        return (global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState)this.Filter;
      }
    }

    public override global::System.Linq.IQueryable<global::Sungero.Docflow.IApprovalRuleBase> ApprovalRulesDataQuery(global::System.Linq.IQueryable<global::Sungero.Docflow.IApprovalRuleBase> query)
    {
      return base.ApprovalRulesDataQuery(query);
    }

    public override global::System.Boolean IsApprovalRulesVisible()
    {
      return base.IsApprovalRulesVisible();
    }

    public override global::System.Linq.IQueryable<global::Sungero.Company.IBusinessUnit> ApprovalRulesBusinessUnitFiltering(global::System.Linq.IQueryable<global::Sungero.Company.IBusinessUnit> query)
    {
      query = base.ApprovalRulesBusinessUnitFiltering(query);
            return query;
    }

    public override global::System.Linq.IQueryable<global::Sungero.Docflow.IDocumentKind> ApprovalRulesDocumentKindFiltering(global::System.Linq.IQueryable<global::Sungero.Docflow.IDocumentKind> query)
    {
      query = base.ApprovalRulesDocumentKindFiltering(query);
            return query;
    }

    public override global::System.Linq.IQueryable<global::Sungero.Company.IDepartment> ApprovalRulesDepartmentFiltering(global::System.Linq.IQueryable<global::Sungero.Company.IDepartment> query)
    {
      query = base.ApprovalRulesDepartmentFiltering(query);
            return query;
    }


    public ApprovalRulesFolderHandlers(global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState filter)
      : base(filter)
    {
    }
  }

}

/// ==================================================================
/// ModuleEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Server
{
  public class ApprovalRulesBusinessUnitPanelNavigationFilter : global::Sungero.Domain.PanelNavigationFilterBase
  {
    public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
    {
      var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Company.IBusinessUnit>)query;
      var typedState = (global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState)this.State;
      var handlers = new global::Sungero.SignatureMark.Module.Docflow.Server.ApprovalRulesFolderHandlers(typedState);
      return handlers.ApprovalRulesBusinessUnitFiltering(typedQuery);
    }
  }

  public class ApprovalRulesDocumentKindPanelNavigationFilter : global::Sungero.Domain.PanelNavigationFilterBase
  {
    public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
    {
      var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Docflow.IDocumentKind>)query;
      var typedState = (global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState)this.State;
      var handlers = new global::Sungero.SignatureMark.Module.Docflow.Server.ApprovalRulesFolderHandlers(typedState);
      return handlers.ApprovalRulesDocumentKindFiltering(typedQuery);
    }
  }

  public class ApprovalRulesDepartmentPanelNavigationFilter : global::Sungero.Domain.PanelNavigationFilterBase
  {
    public override global::System.Linq.IQueryable Apply(global::System.Linq.IQueryable query)
    {
      var typedQuery = (global::System.Linq.IQueryable<global::Sungero.Company.IDepartment>)query;
      var typedState = (global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState)this.State;
      var handlers = new global::Sungero.SignatureMark.Module.Docflow.Server.ApprovalRulesFolderHandlers(typedState);
      return handlers.ApprovalRulesDepartmentFiltering(typedQuery);
    }
  }


}

/// ==================================================================
/// ModuleWidgetHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Server
{
}

/// ==================================================================
/// ModuleQueries.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Queries
{
  public class Module
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.SignatureMark.Server.Sungero.Docflow.ModuleQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}

/// ==================================================================
/// ModuleInitializer.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Server
{
   public  partial class ModuleInitializer:  global::Sungero.Docflow.Server.ModuleInitializer 
  {
  }
}

