
/// ==================================================================
/// Module.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Client
{
  public partial class SmartCaptureModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("f83768c8-f40d-43dd-8cfa-3098f694d645"); }
    }

    public override string Name
    {
      get { return "Sungero.SmartCapture"; }
    }

    public override void RegisterTypes()
    {




      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SmartCapture.Client.IModuleClientPublicFunctions, global::Sungero.SmartCapture.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SmartCapture.Shared.IModuleSharedPublicFunctions, global::Sungero.SmartCapture.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
