
/// ==================================================================
/// ModuleSharedPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Shared
{
  public partial class ModuleSharedPublicFunctions : global::Sungero.SignatureMark.Module.Docflow.Shared.IModuleSharedPublicFunctions
  {
  }
}

/// ==================================================================
/// ModuleFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Functions
{
  internal static partial class Module
  {
    private static object GetFunctionsContainer()
    {
      return new global::Sungero.SignatureMark.Module.Docflow.Shared.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("64f69a45-87e9-428f-8e82-7e6e189907f4");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }
  }
}
namespace Sungero.SignatureMark.Module.Docflow.Shared
{
  public partial class ModuleFunctions: global::Sungero.Docflow.Shared.ModuleFunctions
  {

  }
}

/// ==================================================================
/// ModuleHyperlinks.g.cs
/// ==================================================================

namespace Sungero.SignatureMark.Module.Docflow
{
  public static class DocflowClientFunctionHyperlinksExtensions
  {
  }
}

/// ==================================================================
/// ModuleFoldersFilterStates.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Shared
{

  public class ApprovalRulesFilterState : global::Sungero.Docflow.Shared.ApprovalRulesFilterState,
    global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState
  {


  }


}

/// ==================================================================
/// ModuleResources.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Shared
{
  public class ModuleResources : global::Sungero.Docflow.Shared.ModuleResources, global::Sungero.SignatureMark.Module.Docflow.IModuleResources
  {
  }
}

/// ==================================================================
/// ModuleWidgetParameters.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Module.Docflow.Shared
{  
}
