
/// ==================================================================
/// Module.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SignatureMark.Client
{
  public partial class SignatureMarkModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("b8868f37-48dc-47d0-992a-f65a141ef221"); }
    }

    public override string Name
    {
      get { return "Sungero.SignatureMark"; }
    }

    public override void RegisterTypes()
    {


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SignatureMark.Module.Docflow.FolderFilterState.IApprovalRulesFilterState, global::Sungero.SignatureMark.Module.Docflow.Shared.ApprovalRulesFilterState>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SignatureMark.Module.Docflow.Client.IModuleClientPublicFunctions, global::Sungero.SignatureMark.Module.Docflow.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SignatureMark.Module.Docflow.Shared.IModuleSharedPublicFunctions, global::Sungero.SignatureMark.Module.Docflow.Shared.ModuleSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SignatureMark.Client.IModuleClientPublicFunctions, global::Sungero.SignatureMark.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SignatureMark.Shared.IModuleSharedPublicFunctions, global::Sungero.SignatureMark.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
