
/// ==================================================================
/// Module.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Server
{
  public partial class SmartCaptureModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("f83768c8-f40d-43dd-8cfa-3098f694d645"); }
    }

    public override string Name
    {
      get { return "Sungero.SmartCapture"; }
    }

    public override void RegisterTypes()
    {




      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SmartCapture.Server.IModuleServerPublicFunctions, global::Sungero.SmartCapture.Server.ModuleServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.SmartCapture.Shared.IModuleSharedPublicFunctions, global::Sungero.SmartCapture.Shared.ModuleSharedPublicFunctions>();
    }
  }
}

/// ==================================================================
/// ModuleHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Server
{
}

/// ==================================================================
/// ModuleFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Functions
{
  internal static partial class Module
  {
    private static object GetFunctionsContainer()
    {
      return new global::Sungero.SmartCapture.Server.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType)
    {
      var moduleId = new global::System.Guid("f83768c8-f40d-43dd-8cfa-3098f694d645");
      var finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(moduleId));
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      return moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static).Invoke(null, null);
    }
  }
}

/// ==================================================================
/// ModuleInitializationInstantiation.g.cs
/// ==================================================================



/// ==================================================================
/// ModuleEventArgs.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Server
{
}

/// ==================================================================
/// ModuleServerPublicFunctions.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Server
{
  public partial class ModuleServerPublicFunctions : global::Sungero.SmartCapture.Server.IModuleServerPublicFunctions
  {
  }
}

namespace Sungero.SmartCapture.Server
{
  public partial class ModuleServerPublicFunctions : global::Sungero.SmartCapture.Server.IModuleServerPublicFunctions
  {
  }
}

/// ==================================================================
/// ModuleServerInitializationFunctions.g.cs
/// ==================================================================



/// ==================================================================
/// ModuleWidgetHandlers.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Server
{
}

/// ==================================================================
/// ModuleQueries.g.cs
/// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.SmartCapture.Queries
{
  public class Module
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.SmartCapture.Server.ModuleQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}

/// ==================================================================
/// ModuleInitializer.g.cs
/// ==================================================================


